In [3]:
import numpy as np

# 수치미분 함수

def numerical_derivative(f, x):
    delta_x = 1e-4 # 0.0001
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx = it.multi_index        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x) # f(x+delta_x)
        
        x[idx] = tmp_val - delta_x 
        fx2 = f(x) # f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()   
        
    return grad

# sigmoid 함수

def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [21]:
class LogicGate:
        
    def __init__(self, gate_name, xdata, tdata):
        
        self.name = gate_name
        
        # 입력 데이터, 정답 데이터 초기화
        self.__xdata = xdata.reshape(4,2)  # 4개의 입력데이터 x1, x2 에 대하여 batch 처리 행렬
        self.__tdata = tdata.reshape(4,1)  # 4개의 입력데이터 x1, x2 에 대한 각각의 계산 값 행렬
        
        # 2층 hidden layer unit : 6개 가정,  가중치 W2, 바이어스 b2 초기화
        self.__W2 = np.random.rand(2,6)  # weight, 2 X 6 matrix
        self.__b2 = np.random.rand(6)
        
        # 3층 output layer unit : 1 개 , 가중치 W3, 바이어스 b3 초기화
        self.__W3 = np.random.rand(6,1)
        self.__b3 = np.random.rand(1)
                        
        # 학습률 learning rate 초기화
        self.__learning_rate = 1e-2
    
        print(self.name + " object is created")
            
    def feed_forward(self):        # feed forward 를 통하여 손실함수(cross-entropy) 값 계산
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )    
    
    def loss_val(self):          # 외부 출력을 위한 손실함수(cross-entropy) 값 계산 
        
        delta = 1e-7    # log 무한대 발산 방지
    
        z2 = np.dot(self.__xdata, self.__W2) + self.__b2  # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        # cross-entropy 
        return  -np.sum( self.__tdata*np.log(y + delta) + (1-self.__tdata)*np.log((1 - y)+delta ) )
    
    
    # 수치미분을 이용하여 손실함수가 최소가 될때 까지 학습하는 함수
    def train(self):
        
        f = lambda x : self.feed_forward()
        
        print("Initial loss value = ", self.loss_val())
        
        for step in  range(10001):
            
            self.__W2 -= self.__learning_rate * numerical_derivative(f, self.__W2)
    
            self.__b2 -= self.__learning_rate * numerical_derivative(f, self.__b2)
        
            self.__W3 -= self.__learning_rate * numerical_derivative(f, self.__W3)
    
            self.__b3 -= self.__learning_rate * numerical_derivative(f, self.__b3)
    
            if (step % 400 == 0):
                print("step = ", step, "  , loss value = ", self.loss_val())
                
    
    # query, 즉 미래 값 예측 함수
    def predict(self, xdata):
        
        z2 = np.dot(xdata, self.__W2) + self.__b2         # 은닉층의 선형회귀 값
        a2 = sigmoid(z2)                                  # 은닉층의 출력
        
        z3 = np.dot(a2, self.__W3) + self.__b3            # 출력층의 선형회귀 값
        y = a3 = sigmoid(z3)                              # 출력층의 출력
    
        if y > 0.5:
            result = 1  # True
        else:
            result = 0  # False
    
        return y, result

In [24]:
# AND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 0, 0, 1])

and_obj = LogicGate("AND", xdata, tdata)

and_obj.train()

AND object is created
Initial loss value =  9.594292582848226
step =  0   , loss value =  5.408966979296102
step =  400   , loss value =  0.3410621744084914
step =  800   , loss value =  0.07489812716418105
step =  1200   , loss value =  0.036617302310881686
step =  1600   , loss value =  0.02325918601981627
step =  2000   , loss value =  0.01672645099584845
step =  2400   , loss value =  0.012922250892195659
step =  2800   , loss value =  0.010457889307549902
step =  3200   , loss value =  0.008742749329181483
step =  3600   , loss value =  0.007485901102923723
step =  4000   , loss value =  0.0065284383334366595
step =  4400   , loss value =  0.005776636276509629
step =  4800   , loss value =  0.005171830559987888
step =  5200   , loss value =  0.004675520668764888
step =  5600   , loss value =  0.004261443362562397
step =  6000   , loss value =  0.0039110976106694235
step =  6400   , loss value =  0.003611091447089505
step =  6800   , loss value =  0.003351502932606485
step =  7200 

In [6]:
# AND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(and_obj.predict(data))

(array([0.00028802]), 0)
(array([0.01353927]), 0)
(array([0.01328693]), 0)
(array([0.97562853]), 1)


In [25]:
# OR Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 1])

or_obj = LogicGate("OR", xdata, tdata)

or_obj.train()

OR object is created
Initial loss value =  3.64506356908067
step =  0   , loss value =  3.2254123181685186
step =  400   , loss value =  0.19341120407926238
step =  800   , loss value =  0.052115670649982127
step =  1200   , loss value =  0.027544187097935727
step =  1600   , loss value =  0.018177010937124597
step =  2000   , loss value =  0.013372140258897644
step =  2400   , loss value =  0.010488900260494838
step =  2800   , loss value =  0.008582051670635226
step =  3200   , loss value =  0.007234584439586986
step =  3600   , loss value =  0.0062355598684240765
step =  4000   , loss value =  0.005467408782892968
step =  4400   , loss value =  0.004859670542032433
step =  4800   , loss value =  0.004367666360074979
step =  5200   , loss value =  0.003961756954587237
step =  5600   , loss value =  0.003621539274278652
step =  6000   , loss value =  0.003332528206656356
step =  6400   , loss value =  0.0030841677436738335
step =  6800   , loss value =  0.002868590722392154
step =  72

In [8]:
# OR Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(or_obj.predict(data))

(array([0.027623]), 0)
(array([0.99170146]), 1)
(array([0.99154031]), 1)
(array([0.99953083]), 1)


In [9]:
# NAND Gate 객체 생성 및 training

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([1, 1, 1, 0])

nand_obj = LogicGate("NAND", xdata, tdata)

nand_obj.train()

NAND object is created
Initial loss value =  3.4050465991307632
step =  0   , loss value =  3.372429723259125
step =  400   , loss value =  2.2833001674774285
step =  800   , loss value =  2.1702740005041115
step =  1200   , loss value =  1.9673014462732785
step =  1600   , loss value =  1.608557720202307
step =  2000   , loss value =  1.2133660782698854
step =  2400   , loss value =  0.8995077430521554
step =  2800   , loss value =  0.6669134080093537
step =  3200   , loss value =  0.49983421535037564
step =  3600   , loss value =  0.3821648200982537
step =  4000   , loss value =  0.2993675255690563
step =  4400   , loss value =  0.24032504776015534
step =  4800   , loss value =  0.19734185954338374
step =  5200   , loss value =  0.16531823801771464
step =  5600   , loss value =  0.14090909991249173
step =  6000   , loss value =  0.12190380918790747
step =  6400   , loss value =  0.10681780900528323
step =  6800   , loss value =  0.09463441275915727
step =  7200   , loss value =  0.08

In [10]:
# NAND Gate prediction

test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(nand_obj.predict(data))

(array([0.99996147]), 1)
(array([0.98900145]), 1)
(array([0.98857056]), 1)
(array([0.02372619]), 0)


In [22]:
# XOR Gate 객체 생성

xdata = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])
tdata = np.array([0, 1, 1, 0])


xor_obj = LogicGate("XOR", xdata, tdata)

xor_obj.train()

XOR object is created
Initial loss value =  11.552758598216355
step =  0   , loss value =  8.919375354940893
step =  400   , loss value =  2.4825312535316404
step =  800   , loss value =  1.046478422075064
step =  1200   , loss value =  0.2829775631811242
step =  1600   , loss value =  0.12999737965940356
step =  2000   , loss value =  0.07869781156275307
step =  2400   , loss value =  0.05460314976793281
step =  2800   , loss value =  0.04101062365437634
step =  3200   , loss value =  0.032431941432762665
step =  3600   , loss value =  0.026593004051715944
step =  4000   , loss value =  0.022397055276337095
step =  4400   , loss value =  0.019255672040427607
step =  4800   , loss value =  0.016827239083050834
step =  5200   , loss value =  0.014900982646730019
step =  5600   , loss value =  0.013340401184885154
step =  6000   , loss value =  0.012053527977413214
step =  6400   , loss value =  0.010976327774629657
step =  6800   , loss value =  0.010062954496310962
step =  7200   , los

In [23]:
test_data = np.array([ [0, 0], [0, 1], [1, 0], [1, 1] ])

for data in test_data:
    print(xor_obj.predict(data))

(array([0.00052049]), 0)
(array([0.99814398]), 1)
(array([0.99870038]), 1)
(array([0.00223118]), 0)
