# 데이터 정의

In [1]:
import torch

x_train = torch.Tensor([2, 4, 6, 8, 10,
                        12, 14, 16, 18, 20]).view(10,1)
y_train = torch.Tensor([0, 0, 0, 0, 0,
                        0, 1, 1, 1, 1]).view(10,1)

print(x_train.shape, y_train.shape)

torch.Size([10, 1]) torch.Size([10, 1])


# 신경망 모델 구축

In [2]:
from torch import nn

class MyDeepLearningModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(1,8) # weight 8x1, bias 8
        self.l2 = nn.Linear(8,1) # weight 1x8, bias 1
        self.l3 = nn.Sigmoid()
        
    def forward(self, data):        
        x = self.l1(data)
        x = self.l2(x)
        prediction = self.l3(x)
        return prediction

class MyDeepLearningModel1(nn.Module):
    def __init__(self):
        super().__init__()
        self.deeplearning_stack = nn.Sequential(
            nn.Linear(1, 8),
            nn.Linear(8, 1),
            nn.Sigmoid()
        )
    def forward(self, data):
        prediction = self.deeplearning_stack(data)
        return prediction

In [3]:
deeplearning_model  = MyDeepLearningModel()

for name, child in deeplearning_model.named_children():
    print('[',name, ']' )
    for param in child.parameters():
        print("======")
        print(param)


[ l1 ]
Parameter containing:
tensor([[-0.3943],
        [ 0.9553],
        [ 0.9594],
        [-0.4677],
        [ 0.4200],
        [ 0.1399],
        [-0.5292],
        [-0.6150]], requires_grad=True)
Parameter containing:
tensor([ 0.5413, -0.4272, -0.8608, -0.4075,  0.2035,  0.1745,  0.6689, -0.6651],
       requires_grad=True)
[ l2 ]
Parameter containing:
tensor([[ 0.1777, -0.0789, -0.1068, -0.2480,  0.3020,  0.2588, -0.3001,  0.2183]],
       requires_grad=True)
Parameter containing:
tensor([-0.0802], requires_grad=True)
[ l3 ]


# 손실함수 및 옵티마이저 설정

In [4]:
loss_function = nn.BCELoss()

optimizer = torch.optim.SGD(deeplearning_model.parameters(), lr=1e-1)

In [5]:
nums_epoch = 5000

for epoch in range(nums_epoch+1):

    outputs = deeplearning_model(x_train)

    loss = loss_function(outputs, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print('epoch = ', epoch, ' current loss = ', loss.item())

epoch =  0  current loss =  0.6793440580368042
epoch =  100  current loss =  0.3828432559967041
epoch =  200  current loss =  0.30788177251815796
epoch =  300  current loss =  0.2633592486381531
epoch =  400  current loss =  0.23306997120380402
epoch =  500  current loss =  0.2108081579208374
epoch =  600  current loss =  0.19359561800956726
epoch =  700  current loss =  0.17979642748832703
epoch =  800  current loss =  0.16843003034591675
epoch =  900  current loss =  0.1588670313358307
epoch =  1000  current loss =  0.15068189799785614
epoch =  1100  current loss =  0.14357627928256989
epoch =  1200  current loss =  0.13733471930027008
epoch =  1300  current loss =  0.13179662823677063
epoch =  1400  current loss =  0.12683898210525513
epoch =  1500  current loss =  0.12236884981393814
epoch =  1600  current loss =  0.11830923706293106
epoch =  1700  current loss =  0.11460181325674057
epoch =  1800  current loss =  0.11119749397039413
epoch =  1900  current loss =  0.108056977391242

In [6]:
for name, child in deeplearning_model.named_children():
    for param in child.parameters():
        print(name, param)

l1 Parameter containing:
tensor([[-0.2909],
        [ 0.2733],
        [ 0.5140],
        [ 0.1588],
        [-0.0346],
        [-0.0404],
        [-0.4654],
        [ 0.3911]], requires_grad=True)
l1 Parameter containing:
tensor([ 2.9788, -2.7983, -5.2632, -1.6266,  0.3545,  0.4141,  4.7664, -4.0054],
       requires_grad=True)
l2 Parameter containing:
tensor([[-0.7617,  0.7155,  1.3458,  0.4159, -0.0907, -0.1059, -1.2188,  1.0242]],
       requires_grad=True)
l2 Parameter containing:
tensor([-5.8428], requires_grad=True)


# test data 이용한 예측

In [7]:
deeplearning_model.eval()  

test_data = torch.Tensor([0.5, 3.0, 3.5, 11.0, 13.0, 31.0]).view(6,1)

pred = deeplearning_model(test_data)

logical_value = (pred > 0.5).float()

print(pred)
print(logical_value)

tensor([[2.3275e-12],
        [5.0273e-10],
        [1.4731e-09],
        [1.4627e-02],
        [5.2251e-01],
        [1.0000e+00]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [8]:
# 모델을 다시 학습 모드로 전환시킨다. 
deeplearning_model.train()

MyDeepLearningModel(
  (l1): Linear(in_features=1, out_features=8, bias=True)
  (l2): Linear(in_features=8, out_features=1, bias=True)
  (l3): Sigmoid()
)